### PR TITLE
Added Continuous Integration and CodeQL Analysis

### PR DESCRIPTION
**Pull request by felbinger**
The example go application will be build by GitHub actions, afterwards a docker image is build and uploaded to the [GitHub container registry](https://ghcr.io).

## Continuous Integration

The following docker image tags exist:
* `branch-xxx`, where `xxx` is the branch name
* `edge` for the main branch
* `latest` for the latest tag / release
* `v1`, `v1.0`, `v1.0.0` for the matching tags

image

Make sure to prefix the tags with `v` if you wan't a image for them, I suggest matching the format: [`v\d+\.\d+\.\d+`](https://regexr.com/6v4qh) (Examples: v1.0.0, v14.15.161, ...)

## Create release

I suggest creating new releases using the GitHub actions workflow. The primary advantage is, that the release is made by `github-actions` and the helpwave binary is included
image

Afterwards you should adjust the title (which is the tag name by default) / description of the release.

image

### CODE REVIEW

**Comment by felbinger** [comment]
image

**Review by FoseFx — APPROVED** [review]

**Comment by FoseFx** [comment]
Your PR comment should probably be documented somewhere. Either the Wiki or README.md or another .md file.

**Comment by use-to** [comment]
@felbinger or @FoseFx there are some conflicts here. Can someone take a look at that?

**Comment by FoseFx** [comment]
See #7

**Pull request closed without merging**
