### PR TITLE
feat: update of route names

### PR DESCRIPTION
**Pull request by Florian-Sabonchi**

### CODE REVIEW

**Comment by FoseFx** [comment]
emergency != emergency room

**Comment by Florian-Sabonchi** [comment]
> emergency != emergency room

Yes my misstake  shoud we use something like this emergency-rooms?

**Comment by FoseFx** [comment]
I think emergency-rooms is the way to go. Paths imply hierarchy, and an ER is not a part of an emergency.

**Review by FoseFx — APPROVED** [review]
re-generate the swagger docs, then it's good to go

**Comment by Florian-Sabonchi** [comment]
Already done in this Pull Request see commits

**Pull request merged**
